<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets\nightmare.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NightmareLibrary\NightmareLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
	  <AvaloniaResource Include="Assets\**" />
	  <AvaloniaResource Include="Images\**" />
      <AvaloniaResource Include="Help\**" />
      <AvaloniaResource Include="Music\database.json" />
      <None Remove="Music\replacedb.json" />
      <AvaloniaResource Include="Music\replacedb.json" />
      <None Remove="Music\traverseintrance\traversetown_sd.bcstm" />
      <AvaloniaResource Include="Music\traverseintrance\traversetown_sd.bcstm" />
      <None Remove="Music\traverseintrance\traversetown_recoded.bcstm" />
      <AvaloniaResource Include="Music\traverseintrance\traversetown_recoded.bcstm" />
      <None Remove="Music\traverseintrance\traversetown_hd.bcstm" />
      <AvaloniaResource Include="Music\traverseintrance\traversetown_hd.bcstm" />
      <None Remove="Music\traverseintrance\traversetown_com.bcstm" />
      <AvaloniaResource Include="Music\traverseintrance\traversetown_com.bcstm" />
      <None Remove="Music\traverseintrance\traversetown_coded.bcstm" />
      <AvaloniaResource Include="Music\traverseintrance\traversetown_coded.bcstm" />
      <None Remove="Music\sacreddistance\sacredmoon_sd.bcstm" />
      <AvaloniaResource Include="Music\sacreddistance\sacredmoon_sd.bcstm" />
      <None Remove="Music\sacreddistance\sacredmoon_hd.bcstm" />
      <AvaloniaResource Include="Music\sacreddistance\sacredmoon_hd.bcstm" />
      <None Remove="Music\sacreddistance\sacredmoon_days_sd.bcstm" />
      <AvaloniaResource Include="Music\sacreddistance\sacredmoon_days_sd.bcstm" />
      <None Remove="Music\sacreddistance\sacredmoon_days_hd.bcstm" />
      <AvaloniaResource Include="Music\sacreddistance\sacredmoon_days_hd.bcstm" />
      <None Remove="Music\sacreddistance\mysticmoon_sd.bcstm" />
      <AvaloniaResource Include="Music\sacreddistance\mysticmoon_sd.bcstm" />
      <None Remove="Music\sacreddistance\mysticmoon_hd.bcstm" />
      <AvaloniaResource Include="Music\sacreddistance\mysticmoon_hd.bcstm" />
      <None Remove="Music\handtohand\handinhand_com.bcstm" />
      <AvaloniaResource Include="Music\handtohand\handinhand_com.bcstm" />
      <None Remove="Music\handtohand\handinhand_hd.bcstm" />
      <AvaloniaResource Include="Music\handtohand\handinhand_hd.bcstm" />
      <None Remove="Music\handtohand\handinhand_sd.bcstm" />
      <AvaloniaResource Include="Music\handtohand\handinhand_sd.bcstm" />
      <None Remove="Music\handtohand\nightoffate_hd.bcstm" />
      <AvaloniaResource Include="Music\handtohand\nightoffate_hd.bcstm" />
      <None Remove="Music\handtohand\nightoffate_coded.bcstm" />
      <AvaloniaResource Include="Music\handtohand\nightoffate_coded.bcstm" />
      <None Remove="Music\handtohand\nightoffate_recoded.bcstm" />
      <AvaloniaResource Include="Music\handtohand\nightoffate_recoded.bcstm" />
      <None Remove="Music\handtohand\nightoffate_sd.bcstm" />
      <AvaloniaResource Include="Music\handtohand\nightoffate_sd.bcstm" />
      <None Remove="Music\digitaldomination\bytestriking.bcstm" />
      <AvaloniaResource Include="Music\digitaldomination\bytestriking.bcstm" />
      <None Remove="Music\digitaldomination\bytebashing_hd.bcstm" />
      <AvaloniaResource Include="Music\digitaldomination\bytebashing_hd.bcstm" />
      <None Remove="Music\digitaldomination\bytebashing_sd.bcstm" />
      <AvaloniaResource Include="Music\digitaldomination\bytebashing_sd.bcstm" />
      <None Remove="Music\deepdrop\deepdrive_sd.bcstm" />
      <AvaloniaResource Include="Music\deepdrop\deepdrive_sd.bcstm" />
      <None Remove="Music\deepdrop\criticaldrive_sd.bcstm" />
      <AvaloniaResource Include="Music\deepdrop\criticaldrive_sd.bcstm" />
      <None Remove="Music\deepdrop\criticaldrive_hd.bcstm" />
      <AvaloniaResource Include="Music\deepdrop\criticaldrive_hd.bcstm" />
      <None Remove="Music\deepdrop\deepdrive_hd.bcstm" />
      <AvaloniaResource Include="Music\deepdrop\deepdrive_hd.bcstm" />
      <None Remove="Music\accessthegrid\spaceparanoids_sd.bcstm" />
      <AvaloniaResource Include="Music\accessthegrid\spaceparanoids_sd.bcstm" />
      <None Remove="Music\accessthegrid\spaceparanoids_hd.bcstm" />
      <AvaloniaResource Include="Music\accessthegrid\spaceparanoids_hd.bcstm" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="DDD-Toolkit\BCSAR Tool.exe" />
    <None Remove="DDD-Toolkit\ctr_WaveConverter32.7z" />
    <None Remove="DDD-Toolkit\DDD Toolkit.exe" />
    <None Remove="DDD-Toolkit\ETC.exe" />
    <None Remove="DDD-Toolkit\kh3dswizzler.exe" />
    <None Remove="DDD-Toolkit\LZOvlCUE.exe" />
    <None Remove="DDD-Toolkit\Wii3DSUSoundTool.exe" />
    <None Remove="DDD-Toolkit\Yata+.7z" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\nightmare.ico" />
    <Content Include="DDD-Toolkit\BCSAR Tool.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DDD-Toolkit\ctr_WaveConverter32.7z">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DDD-Toolkit\DDD Toolkit.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DDD-Toolkit\ETC.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DDD-Toolkit\kh3dswizzler.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DDD-Toolkit\LZOvlCUE.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DDD-Toolkit\Wii3DSUSoundTool.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DDD-Toolkit\Yata+.7z">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.20" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.3.20" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.20" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.20" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.20" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.20" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="LibGit2Sharp" Version="0.32.0" />
    <PackageReference Include="Markdown.Avalonia" Version="11.0.3" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.3.1.1" />
    <PackageReference Include="SharpCompress" Version="0.50.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.9.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Deploy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DownloadSel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DownloadUnsel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Gamebanana.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Github.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\help.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\InstallArchive.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ModsSel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ModsUnsel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\MusicSel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\MusicUnsel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\nightmare.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\OpenFolder.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\plus.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Preview0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Preview1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Preview2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Preview3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\queue.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Refresh.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\return.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\SettingsSel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\SettingsUnsel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\sora.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\transrights.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\unqueue.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Web.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Music\database.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Managers\Manager.axaml.cs">
      <DependentUpon>Manager.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Managers\NewManager.axaml.cs">
      <DependentUpon>NewManager.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\MenuButton.axaml.cs">
      <DependentUpon>MenuButton.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\ConfigSlot.axaml.cs">
      <DependentUpon>ConfigSlot.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\ImageButton.axaml.cs">
      <DependentUpon>ImageButton.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\MusicSlot.axaml.cs">
      <DependentUpon>MusicSlot.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>
