name: Create all builds
run-name: Creating builds for multiple targets
on: [workflow_dispatch, release]
jobs:
  Build-Builds-From-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run build script
        run: |
          cd ${{ github.workspace }}
          sudo mkdir dist
          sudo mkdir dist/zip
          sudo bash build-all.sh

      - name: Upload win-x64
        uses: actions/upload-artifact@v4
        with:
          name: win-x64.zip
          path: dist/zip/win-x64.zip

      - name: Upload win-arm64
        uses: actions/upload-artifact@v4
        with:
          name: win-arm64.zip
          path: dist/zip/win-arm64.zip

      - name: Upload win-x86
        uses: actions/upload-artifact@v4
        with:
          name: win-x86.zip
          path: dist/zip/win-x86.zip

      - name: Upload linux-x64
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64.zip
          path: dist/zip/linux-x64.zip

      - name: Upload linux-arm64
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64.zip
          path: dist/zip/linux-arm64.zip

      - name: Upload linux-arm
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm.zip
          path: dist/zip/linux-arm.zip

      - name: Upload osx-x64
        uses: actions/upload-artifact@v4
        with:
          name: osx-x64.zip
          path: dist/zip/osx-x64.zip

      - name: Upload osx-arm64
        uses: actions/upload-artifact@v4
        with:
          name: osx-arm64.zip
          path: dist/zip/osx-arm64.zip
  Build-Flatpak-From-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Install flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak
          sudo apt-get install -y flatpak-builder

      - name: Add flathub
        run: |
          sudo flatpak remote-add --if-not-exists flathub \
            https://dl.flathub.org/repo/flathub.flatpakrepo
    
      - name: Check out repository code
        uses: actions/checkout@v6
        
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run build script
        run: |
          cd ${{ github.workspace }}
          sudo bash build-flatpak.sh

      - name: Upload flatpak
        uses: actions/upload-artifact@v4
        with:
          name: nightmare-editor.flatpak
          path: flatpak/nightmare-editor.flatpak
