name: Create all builds
run-name: Creating builds for multiple targets
on:
  release:
    types: [published]
  workflow_dispatch: {}
jobs:
  Build-Builds-From-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run build script
        run: |
          cd ${{ github.workspace }}
          sudo mkdir dist
          sudo mkdir dist/zip
          sudo bash build-all.sh

      - name: Upload win-x64
        uses: actions/upload-artifact@v7
        with:
          path: dist/zip/win-x64.zip
          archive: false

      - name: Upload win-arm64
        uses: actions/upload-artifact@v7
        with:
          path: dist/zip/win-arm64.zip
          archive: false
          
      - name: Upload win-x86
        uses: actions/upload-artifact@v7
        with:
          path: dist/zip/win-x86.zip
          archive: false

      - name: Upload linux-x64
        uses: actions/upload-artifact@v7
        with:
          path: dist/zip/linux-x64.zip
          archive: false

      - name: Upload linux-arm64
        uses: actions/upload-artifact@v7
        with:
          path: dist/zip/linux-arm64.zip
          archive: false

      - name: Upload linux-arm
        uses: actions/upload-artifact@v7
        with:
          path: dist/zip/linux-arm.zip
          archive: false

      - name: Upload osx-x64
        uses: actions/upload-artifact@v7
        with:
          path: dist/zip/osx-x64.zip
          archive: false

      - name: Upload osx-arm64
        uses: actions/upload-artifact@v7
        with:
          path: dist/zip/osx-arm64.zip
          archive: false

  Build-Flatpak-From-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Install flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak
          sudo apt-get install -y flatpak-builder

      - name: Add flathub
        run: |
          sudo flatpak remote-add --if-not-exists flathub \
            https://dl.flathub.org/repo/flathub.flatpakrepo
    
      - name: Check out repository code
        uses: actions/checkout@v6
        
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run build script
        run: |
          cd ${{ github.workspace }}
          sudo bash build-flatpak.sh

      - name: Upload flatpak
        uses: actions/upload-artifact@v7
        with:
          path: flatpak/nightmare-editor.flatpak
          archive: false

  Build-Arm-Flatpak-From-Script:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak
          sudo apt-get install -y flatpak-builder

      - name: Add flathub
        run: |
          sudo flatpak remote-add --if-not-exists flathub \
            https://dl.flathub.org/repo/flathub.flatpakrepo
    
      - name: Check out repository code
        uses: actions/checkout@v6
        
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run build script
        run: |
          cd ${{ github.workspace }}
          sudo bash build-flatpak.sh
          mv flatpak/nightmare-editor.flatpak flatpak/nightmare-editor-arm.flatpak

      - name: Upload flatpak
        uses: actions/upload-artifact@v7
        with:
          path: flatpak/nightmare-editor-arm.flatpak
          archive: false
