name: Create all builds
run-name: Creating builds for multiple targets
on: [push]
jobs:
  Build-Builds-From-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run build script
        run: |
          cd ${{ github.workspace }}
          sudo mkdir dist
          sudo mkdir dist/zip
          sudo bash build-all.sh

      - name: Upload folder
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: dist/zip/*
